Fix this weirdness

diff --git a/unicorn_script b/unicorn_script
--- a/unicorn_script
+++ b/unicorn_script
@@ -12,19 +12,19 @@
 
 set -e
 
-USAGE=\"Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>\"
+USAGE="Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"
 
 # app settings
-USER=\"ubuntu\"
-APP_NAME=\"cs_493_hw9\"
-APP_ROOT=\"/home/$USER/$APP_NAME\"
-ENV=\"production\"
+USER="ubuntu"
+APP_NAME="cs_493_hw9"
+APP_ROOT="/home/$USER/$APP_NAME"
+ENV="production"
 
 # environment settings
-PATH=\"/home/$USER/.rbenv/shims:/home/$USER/.rbenv/bin:$PATH\"
-CMD=\"cd $APP_ROOT && bundle exec unicorn -c config/unicorn.rb -E $ENV -D\"
-PID=\"$APP_ROOT/shared/pids/unicorn.pid\"
-OLD_PID=\"$PID.oldbin\"
+PATH="/home/$USER/.rbenv/shims:/home/$USER/.rbenv/bin:$PATH"
+CMD="cd $APP_ROOT && bundle exec unicorn -c config/unicorn.rb -E $ENV -D"
+PID="$APP_ROOT/shared/pids/unicorn.pid"
+OLD_PID="$PID.oldbin"
 
 # make sure the app exists
 cd $APP_ROOT || exit 1
@@ -39,28 +39,28 @@ oldsig () {
 
 case $1 in
   start)
-    sig 0 && echo >&2 \"Already running\" && exit 0
-    echo \"Starting $APP_NAME\"
-    su - $USER -c \"$CMD\"
+    sig 0 && echo >&2 "Already running" && exit 0
+    echo "Starting $APP_NAME"
+    su - $USER -c "$CMD"
     ;;
   stop)
-    echo \"Stopping $APP_NAME\"
+    echo "Stopping $APP_NAME"
     sig QUIT && exit 0
-    echo >&2 \"Not running\"
+    echo >&2 "Not running"
     ;;
   force-stop)
-    echo \"Force stopping $APP_NAME\"
+    echo "Force stopping $APP_NAME"
     sig TERM && exit 0
-    echo >&2 \"Not running\"
+    echo >&2 "Not running"
     ;;
   restart|reload|upgrade)
-    sig USR2 && echo \"reloaded $APP_NAME\" && exit 0
-    echo >&2 \"Couldn't reload, starting '$CMD' instead\"
+    sig USR2 && echo "reloaded $APP_NAME" && exit 0
+    echo >&2 "Couldn't reload, starting '$CMD' instead"
     $CMD
     ;;
   rotate)
     sig USR1 && echo rotated logs OK && exit 0
-    echo >&2 \"Couldn't rotate logs\" && exit 1
+    echo >&2 "Couldn't rotate logs" && exit 1
     ;;
   *)
     echo >&2 $USAGE
